openapi: "3.0.3"
info:
  title: Bookstore API
  version: "1.0.0"
  description: A simple bookstore API for managing books and authors.
servers:
  - url: https://bookstore.example.com/api/v1
paths:
  /books:
    get:
      operationId: listBooks
      summary: List all books
      tags: [books]
      parameters:
        - name: genre
          in: query
          description: Filter by genre
          schema:
            type: string
        - name: limit
          in: query
          description: Max results to return
          schema:
            type: integer
            default: 20
      responses:
        "200":
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    post:
      operationId: createBook
      summary: Add a new book
      tags: [books]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookInput"
      responses:
        "201":
          description: Book created
  /books/{bookId}:
    get:
      operationId: getBook
      summary: Get a book by ID
      tags: [books]
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single book
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
    delete:
      operationId: deleteBook
      summary: Delete a book
      tags: [books]
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Book deleted
  /authors:
    get:
      operationId: listAuthors
      summary: List all authors
      tags: [authors]
      responses:
        "200":
          description: A list of authors
    post:
      operationId: createAuthor
      summary: Add a new author
      tags: [authors]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name]
              properties:
                name:
                  type: string
                bio:
                  type: string
      responses:
        "201":
          description: Author created
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        price:
          type: number
    BookInput:
      type: object
      required: [title, author]
      properties:
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        price:
          type: number
